import { createContext, useContext, useLayoutEffect, useMemo, useState } from "react";

const LANGUAGE_KEY = "atiSiteLanguage";

export const languageOptions = [
  { code: "en", label: "English", shortLabel: "EN" },
  { code: "ta", label: "தமிழ்", shortLabel: "தமிழ்" },
  { code: "si", label: "සිංහල", shortLabel: "සිං" },
];

const translations = {
  en: {
    "language.label": "Language",
    "brand.subtitle": "Advanced Technological Institute",
    "brand.parent": "Sri Lanka Institute of Advanced Technological Education",
    "nav.home": "Home",
    "nav.about": "About",
    "nav.faculties": "Faculties",
    "nav.courses": "Courses",
    "nav.news": "News",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.register": "Register",
    "theme.light": "Light",
    "theme.dark": "Dark",
    "theme.switchLight": "Switch to light theme",
    "theme.switchDark": "Switch to dark theme",
    "footer.description": "Empowering students through quality education, practical skills, and community-minded learning.",
    "footer.contact": "Contact",
    "footer.campus": "Campus",
    "footer.location": "Jaffna, Northern Province, Sri Lanka",
    "common.viewCourses": "View Courses",
    "common.readBlog": "Read Blog",
    "common.noBlogs": "No Blogs",
    "common.noBlogsText": "No published blogs yet.",
    "common.noBlogsHint": "Admin-published blogs will appear here.",
    "home.institute": "Sri Lanka Institute of Advanced Technological Education.",
    "home.heroTitle": "Advanced Technological Institute Jaffna",
    "home.heroText": "Empowering Students Through Quality Education",
    "home.notices": "Notices",
    "home.latestAnnouncements": "Latest Announcements",
    "home.noticesText": "Important updates for students, staff, and the wider ATI community.",
    "home.campusLife": "Campus Life",
    "home.campusTitle": "A focused place to learn, connect, and grow",
    "home.campusText": "From lecture rooms to student activities, ATI Jaffna supports a practical and welcoming learning experience.",
    "home.pathways": "Pathways",
    "home.popularCourses": "Popular Courses",
    "home.coursesText": "Industry-aware programmes designed to build knowledge, confidence, and practical skills.",
    "home.departments": "Departments",
    "home.communities": "Learning Communities",
    "home.departmentsText": "Focused academic communities that help students build the right professional foundation.",
    "home.news": "News",
    "home.events": "Campus Events",
    "home.eventsText": "Keep up with institute announcements, activities, and student achievements.",
    "chat.title": "Ask ATI Buddy",
    "chat.subtitle": "Your friendly campus guide",
    "chat.online": "Online now",
    "chat.popular": "Popular questions",
    "chat.prompt": "Ask ATI Buddy anything about ATI Jaffna, login, courses, or study help.",
    "chat.placeholder": "Ask ATI Buddy a question...",
    "chat.send": "Send message",
    "chat.clear": "Clear chat",
    "chat.welcome": "Hi! I am ATI Buddy. Ask me anything about ATI Jaffna, student login, courses, campus life, study help, or general questions.",
    "chat.questionCourses": "What courses are available?",
    "chat.questionContact": "How can I contact ATI Jaffna?",
    "chat.questionLogin": "How do I log in and open Student Portal?",
    "portal.portal": "Portal",
    "portal.dashboard": "Dashboard",
    "portal.userApprovals": "User Approvals",
    "portal.studentManagement": "Student Management",
    "portal.facultyManagement": "Faculty Management",
    "portal.courseManagement": "Course Management",
    "portal.assignmentPortal": "Assignment Portal",
    "portal.gradeManagement": "Grade Management",
    "portal.adminMessages": "Admin Messages",
    "portal.aiAssistant": "AI Assistant",
    "portal.pageCustomization": "Page Customization",
    "portal.systemSettings": "System Settings",
    "portal.profile": "Profile",
    "portal.timetable": "Timetable",
    "portal.assignments": "Assignments",
    "portal.grades": "Grades",
    "portal.attendance": "Attendance",
    "portal.messages": "Messages",
    "portal.notifications": "Notifications",
    "portal.resources": "Resources",
    "portal.students": "Students",
    "portal.courses": "Courses",
    "portal.logout": "Logout",
    "portal.signedIn": "Signed in as",
    "portal.openNav": "Open navigation",
    "portal.closeNav": "Close navigation",
    "page.aboutTitle": "A Practical Higher Education Campus in Jaffna",
    "page.aboutText": "ATI Jaffna supports students with technology-focused education, professional pathways, and a campus culture built around growth.",
    "page.facultiesText": "Explore the academic areas available at ATI Jaffna.",
    "page.coursesTitle": "Higher National Diploma Programmes",
    "page.coursesText": "Explore course pathways and contact ATI Jaffna for programme details.",
    "page.contactTitle": "Get in Touch",
    "page.contactText": "Send a message to ATI Jaffna or visit the campus office for support.",
    "page.fullName": "Full name",
    "page.email": "Email address",
    "page.subject": "Subject",
    "page.message": "Message",
    "page.sendMessage": "Send Message",
    "auth.loginTitle": "Sign in to your ATI Jaffna workspace",
    "auth.loginText": "Access your dashboard, academic records, notices, and learning tools.",
    "auth.official": "Official digital workspace",
    "auth.portalAccess": "Portal access",
    "auth.welcome": "Welcome back",
    "auth.welcomeText": "Sign in once and we will open the right dashboard for your account.",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter password",
    "auth.signIn": "Sign in",
    "auth.signingIn": "Signing in...",
    "auth.newUser": "New to ATI Jaffna?",
    "auth.createAccount": "Create an account",
    "auth.registerTitle": "Create your ATI portal account",
    "auth.registerText": "Build a complete student profile with academic pathway, department, intake, and emergency contact details.",
    "auth.studentBenefits": "Student portal benefits",
    "auth.requestAccess": "Request access",
    "auth.requestAccessText": "Create an active student account with academic details.",
    "auth.submitRegistration": "Submit registration",
    "auth.creatingAccount": "Creating account...",
    "auth.hasAccount": "Already have an account?",
    "portal.student": "Student",
    "portal.admin": "Admin",
    "portal.faculty": "Faculty",
    "portal.classTimetable": "Class Timetable",
    "portal.departmentMessages": "Department Messages",
    "portal.studentSettings": "Student Settings",
    "portal.fees": "Fees",
    "portal.studentProgress": "Student Progress",
  },
  ta: {
    "language.label": "மொழி",
    "brand.subtitle": "உயர் தொழில்நுட்ப நிறுவனம்",
    "brand.parent": "இலங்கை உயர் தொழில்நுட்பக் கல்வி நிறுவனம்",
    "nav.home": "முகப்பு",
    "nav.about": "எங்களைப் பற்றி",
    "nav.faculties": "பீடங்கள்",
    "nav.courses": "பாடநெறிகள்",
    "nav.news": "செய்திகள்",
    "nav.contact": "தொடர்பு",
    "nav.login": "உள்நுழை",
    "nav.register": "பதிவு",
    "theme.light": "ஒளி",
    "theme.dark": "இருள்",
    "theme.switchLight": "ஒளி தோற்றத்திற்கு மாற்று",
    "theme.switchDark": "இருள் தோற்றத்திற்கு மாற்று",
    "footer.description": "தரமான கல்வி, நடைமுறைத் திறன்கள் மற்றும் சமூக அக்கறையுள்ள கற்றல் மூலம் மாணவர்களை வலுப்படுத்துகிறோம்.",
    "footer.contact": "தொடர்பு",
    "footer.campus": "வளாகம்",
    "footer.location": "யாழ்ப்பாணம், வட மாகாணம், இலங்கை",
    "common.viewCourses": "பாடநெறிகளைப் பார்க்க",
    "common.readBlog": "வலைப்பதிவைப் படிக்க",
    "common.noBlogs": "வலைப்பதிவுகள் இல்லை",
    "common.noBlogsText": "வெளியிடப்பட்ட வலைப்பதிவுகள் இன்னும் இல்லை.",
    "common.noBlogsHint": "நிர்வாகி வெளியிடும் வலைப்பதிவுகள் இங்கே தோன்றும்.",
    "home.institute": "உயர் தொழில்நுட்ப நிறுவனம்",
    "home.heroTitle": "ATI யாழ்ப்பாணம்",
    "home.heroText": "தரமான கல்வி மூலம் மாணவர்களை வலுப்படுத்துதல்",
    "home.notices": "அறிவிப்புகள்",
    "home.latestAnnouncements": "சமீபத்திய அறிவிப்புகள்",
    "home.noticesText": "மாணவர்கள், பணியாளர்கள் மற்றும் ATI சமூகத்திற்கான முக்கிய புதுப்பிப்புகள்.",
    "home.campusLife": "வளாக வாழ்க்கை",
    "home.campusTitle": "கற்க, இணைக்க மற்றும் வளர சிறந்த இடம்",
    "home.campusText": "விரிவுரை அறைகள் முதல் மாணவர் செயல்பாடுகள் வரை, ATI யாழ்ப்பாணம் நடைமுறையான மற்றும் வரவேற்கும் கற்றல் அனுபவத்தை வழங்குகிறது.",
    "home.pathways": "கற்றல் பாதைகள்",
    "home.popularCourses": "பிரபலமான பாடநெறிகள்",
    "home.coursesText": "அறிவு, நம்பிக்கை மற்றும் நடைமுறைத் திறன்களை வளர்க்க வடிவமைக்கப்பட்ட தொழில்துறை சார்ந்த பாடநெறிகள்.",
    "home.departments": "துறைகள்",
    "home.communities": "கற்றல் சமூகங்கள்",
    "home.departmentsText": "மாணவர்கள் சரியான தொழில்முறை அடித்தளத்தை உருவாக்க உதவும் கல்விச் சமூகங்கள்.",
    "home.news": "செய்திகள்",
    "home.events": "வளாக நிகழ்வுகள்",
    "home.eventsText": "நிறுவன அறிவிப்புகள், செயல்பாடுகள் மற்றும் மாணவர் சாதனைகளை அறிந்துகொள்ளுங்கள்.",
    "chat.title": "ATI Buddy-யிடம் கேளுங்கள்",
    "chat.subtitle": "உங்கள் நட்பான வளாக வழிகாட்டி",
    "chat.online": "இப்போது இணையத்தில்",
    "chat.popular": "பிரபலமான கேள்விகள்",
    "chat.prompt": "ATI யாழ்ப்பாணம் பற்றி பொதுவான கேள்வியைக் கேளுங்கள்.",
    "chat.placeholder": "ATI Buddy-யிடம் ஒரு கேள்வியைக் கேளுங்கள்...",
    "chat.send": "செய்தியை அனுப்பு",
    "chat.clear": "உரையாடலை அழி",
    "chat.welcome": "வணக்கம்! நான் ATI Buddy. ATI யாழ்ப்பாணம் பற்றி ஒரு கேள்வியைக் கேளுங்கள்.",
    "chat.questionCourses": "என்ன பாடநெறிகள் உள்ளன?",
    "chat.questionContact": "ATI யாழ்ப்பாணத்தை எவ்வாறு தொடர்புகொள்வது?",
    "chat.questionLogin": "எனது தளத்தில் எவ்வாறு உள்நுழைவது?",
    "portal.portal": "தளம்",
    "portal.dashboard": "முகப்புப் பலகை",
    "portal.userApprovals": "பயனர் அனுமதிகள்",
    "portal.studentManagement": "மாணவர் மேலாண்மை",
    "portal.facultyManagement": "விரிவுரையாளர் மேலாண்மை",
    "portal.courseManagement": "பாடநெறி மேலாண்மை",
    "portal.assignmentPortal": "பணிகள் தளம்",
    "portal.gradeManagement": "மதிப்பெண் மேலாண்மை",
    "portal.adminMessages": "நிர்வாகச் செய்திகள்",
    "portal.aiAssistant": "AI உதவியாளர்",
    "portal.pageCustomization": "பக்க தனிப்பயனாக்கம்",
    "portal.systemSettings": "கணினி அமைப்புகள்",
    "portal.profile": "சுயவிவரம்",
    "portal.timetable": "நேர அட்டவணை",
    "portal.assignments": "பணிகள்",
    "portal.grades": "மதிப்பெண்கள்",
    "portal.attendance": "வருகை",
    "portal.messages": "செய்திகள்",
    "portal.notifications": "அறிவிப்புகள்",
    "portal.resources": "வளங்கள்",
    "portal.students": "மாணவர்கள்",
    "portal.courses": "பாடநெறிகள்",
    "portal.logout": "வெளியேறு",
    "portal.signedIn": "உள்நுழைந்தவர்",
    "portal.openNav": "வழிசெலுத்தலைத் திற",
    "portal.closeNav": "வழிசெலுத்தலை மூடு",
    "page.aboutTitle": "யாழ்ப்பாணத்தில் நடைமுறை உயர்கல்வி வளாகம்",
    "page.aboutText": "ATI யாழ்ப்பாணம் தொழில்நுட்பக் கல்வி, தொழில்முறைப் பாதைகள் மற்றும் வளர்ச்சியை மையமாகக் கொண்ட வளாகப் பண்பாடு மூலம் மாணவர்களை ஆதரிக்கிறது.",
    "page.facultiesText": "ATI யாழ்ப்பாணத்தில் உள்ள கல்வித் துறைகளை அறிந்துகொள்ளுங்கள்.",
    "page.coursesTitle": "உயர் தேசிய டிப்ளோமா பாடநெறிகள்",
    "page.coursesText": "பாடநெறிகளை அறிந்து, மேலதிக விவரங்களுக்கு ATI யாழ்ப்பாணத்தை தொடர்புகொள்ளுங்கள்.",
    "page.contactTitle": "தொடர்புகொள்ளுங்கள்",
    "page.contactText": "ATI யாழ்ப்பாணத்திற்கு செய்தி அனுப்புங்கள் அல்லது உதவிக்காக வளாக அலுவலகத்தை அணுகுங்கள்.",
    "page.fullName": "முழுப் பெயர்",
    "page.email": "மின்னஞ்சல் முகவரி",
    "page.subject": "பொருள்",
    "page.message": "செய்தி",
    "page.sendMessage": "செய்தியை அனுப்பு",
    "auth.loginTitle": "உங்கள் ATI யாழ்ப்பாண பணித்தளத்தில் உள்நுழையுங்கள்",
    "auth.loginText": "உங்கள் முகப்புப் பலகை, கல்விப் பதிவுகள், அறிவிப்புகள் மற்றும் கற்றல் கருவிகளை அணுகுங்கள்.",
    "auth.official": "அதிகாரப்பூர்வ டிஜிட்டல் பணித்தளம்",
    "auth.portalAccess": "தள அணுகல்",
    "auth.welcome": "மீண்டும் வரவேற்கிறோம்",
    "auth.welcomeText": "ஒருமுறை உள்நுழையுங்கள்; உங்கள் கணக்கிற்கான சரியான முகப்புப் பலகையைத் திறப்போம்.",
    "auth.password": "கடவுச்சொல்",
    "auth.passwordPlaceholder": "கடவுச்சொல்லை உள்ளிடுங்கள்",
    "auth.signIn": "உள்நுழை",
    "auth.signingIn": "உள்நுழைகிறது...",
    "auth.newUser": "ATI யாழ்ப்பாணத்திற்கு புதியவரா?",
    "auth.createAccount": "கணக்கை உருவாக்கு",
    "auth.registerTitle": "உங்கள் ATI தளக் கணக்கை உருவாக்குங்கள்",
    "auth.registerText": "கல்விப் பாதை, துறை, சேர்க்கை மற்றும் அவசரத் தொடர்பு விவரங்களுடன் முழுமையான மாணவர் சுயவிவரத்தை உருவாக்குங்கள்.",
    "auth.studentBenefits": "மாணவர் தளத்தின் நன்மைகள்",
    "auth.requestAccess": "அணுகலைக் கோருங்கள்",
    "auth.requestAccessText": "கல்வி விவரங்களுடன் செயலில் உள்ள மாணவர் கணக்கை உருவாக்குங்கள்.",
    "auth.submitRegistration": "பதிவை சமர்ப்பி",
    "auth.creatingAccount": "கணக்கு உருவாக்கப்படுகிறது...",
    "auth.hasAccount": "ஏற்கனவே கணக்கு உள்ளதா?",
    "portal.student": "மாணவர்",
    "portal.admin": "நிர்வாகி",
    "portal.faculty": "விரிவுரையாளர்",
    "portal.classTimetable": "வகுப்பு நேர அட்டவணை",
    "portal.departmentMessages": "துறைச் செய்திகள்",
    "portal.studentSettings": "மாணவர் அமைப்புகள்",
    "portal.fees": "கட்டணங்கள்",
    "portal.studentProgress": "மாணவர் முன்னேற்றம்",
  },
  si: {
    "language.label": "භාෂාව",
    "brand.subtitle": "උසස් තාක්ෂණ ආයතනය",
    "brand.parent": "ශ්‍රී ලංකා උසස් තාක්ෂණ අධ්‍යාපන ආයතනය",
    "nav.home": "මුල් පිටුව",
    "nav.about": "අප ගැන",
    "nav.faculties": "පීඨ",
    "nav.courses": "පාඨමාලා",
    "nav.news": "පුවත්",
    "nav.contact": "සම්බන්ධ වන්න",
    "nav.login": "පිවිසෙන්න",
    "nav.register": "ලියාපදිංචි වන්න",
    "theme.light": "ආලෝක",
    "theme.dark": "අඳුරු",
    "theme.switchLight": "ආලෝක තේමාවට මාරු වන්න",
    "theme.switchDark": "අඳුරු තේමාවට මාරු වන්න",
    "footer.description": "ගුණාත්මක අධ්‍යාපනය, ප්‍රායෝගික කුසලතා සහ ප්‍රජාමූලික ඉගෙනීම මඟින් සිසුන් සවිබල ගන්වයි.",
    "footer.contact": "සම්බන්ධ වන්න",
    "footer.campus": "කැම්පස්",
    "footer.location": "යාපනය, උතුරු පළාත, ශ්‍රී ලංකාව",
    "common.viewCourses": "පාඨමාලා බලන්න",
    "common.readBlog": "බ්ලොග් ලිපිය කියවන්න",
    "common.noBlogs": "බ්ලොග් ලිපි නැත",
    "common.noBlogsText": "තවමත් පළ කළ බ්ලොග් ලිපි නොමැත.",
    "common.noBlogsHint": "පරිපාලක පළ කරන බ්ලොග් ලිපි මෙහි පෙන්වනු ඇත.",
    "home.institute": "උසස් තාක්ෂණ ආයතනය",
    "home.heroTitle": "ATI යාපනය",
    "home.heroText": "ගුණාත්මක අධ්‍යාපනය තුළින් සිසුන් සවිබල ගැන්වීම",
    "home.notices": "නිවේදන",
    "home.latestAnnouncements": "නවතම නිවේදන",
    "home.noticesText": "සිසුන්, කාර්ය මණ්ඩලය සහ ATI ප්‍රජාව සඳහා වැදගත් යාවත්කාලීන.",
    "home.campusLife": "කැම්පස් ජීවිතය",
    "home.campusTitle": "ඉගෙනීමට, සම්බන්ධ වීමට සහ වර්ධනය වීමට සුදුසු ස්ථානයක්",
    "home.campusText": "දේශන ශාලාවල සිට ශිෂ්‍ය ක්‍රියාකාරකම් දක්වා ATI යාපනය ප්‍රායෝගික සහ පිළිගැනීමේ ඉගෙනුම් අත්දැකීමක් සපයයි.",
    "home.pathways": "ඉගෙනුම් මාර්ග",
    "home.popularCourses": "ජනප්‍රිය පාඨමාලා",
    "home.coursesText": "දැනුම, විශ්වාසය සහ ප්‍රායෝගික කුසලතා වර්ධනය සඳහා සැලසුම් කළ කර්මාන්තයට ගැළපෙන වැඩසටහන්.",
    "home.departments": "දෙපාර්තමේන්තු",
    "home.communities": "ඉගෙනුම් ප්‍රජාවන්",
    "home.departmentsText": "නිවැරදි වෘත්තීය පදනම ගොඩනැගීමට සිසුන්ට උපකාර කරන අධ්‍යයන ප්‍රජාවන්.",
    "home.news": "පුවත්",
    "home.events": "කැම්පස් සිදුවීම්",
    "home.eventsText": "ආයතන නිවේදන, ක්‍රියාකාරකම් සහ ශිෂ්‍ය ජයග්‍රහණ දැනගන්න.",
    "chat.title": "ATI Buddy ගෙන් අසන්න",
    "chat.subtitle": "ඔබේ හිතකාමී කැම්පස් මාර්ගෝපදේශකයා",
    "chat.online": "දැන් සබැඳිව",
    "chat.popular": "ජනප්‍රිය ප්‍රශ්න",
    "chat.prompt": "ATI යාපනය පිළිබඳ සාමාන්‍ය ප්‍රශ්නයක් අසන්න.",
    "chat.placeholder": "ATI Buddy ගෙන් ප්‍රශ්නයක් අසන්න...",
    "chat.send": "පණිවිඩය යවන්න",
    "chat.clear": "සංවාදය ඉවත් කරන්න",
    "chat.welcome": "ආයුබෝවන්! මම ATI Buddy. ATI යාපනය පිළිබඳ ප්‍රශ්නයක් අසන්න.",
    "chat.questionCourses": "ලබා ගත හැකි පාඨමාලා මොනවාද?",
    "chat.questionContact": "ATI යාපනය සම්බන්ධ කරගන්නේ කෙසේද?",
    "chat.questionLogin": "මගේ ද්වාරයට පිවිසෙන්නේ කෙසේද?",
    "portal.portal": "ද්වාරය",
    "portal.dashboard": "උපකරණ පුවරුව",
    "portal.userApprovals": "පරිශීලක අනුමැති",
    "portal.studentManagement": "ශිෂ්‍ය කළමනාකරණය",
    "portal.facultyManagement": "කථිකාචාර්ය කළමනාකරණය",
    "portal.courseManagement": "පාඨමාලා කළමනාකරණය",
    "portal.assignmentPortal": "පැවරුම් ද්වාරය",
    "portal.gradeManagement": "ශ්‍රේණි කළමනාකරණය",
    "portal.adminMessages": "පරිපාලක පණිවිඩ",
    "portal.aiAssistant": "AI සහායක",
    "portal.pageCustomization": "පිටු අභිරුචිකරණය",
    "portal.systemSettings": "පද්ධති සැකසුම්",
    "portal.profile": "පැතිකඩ",
    "portal.timetable": "කාලසටහන",
    "portal.assignments": "පැවරුම්",
    "portal.grades": "ශ්‍රේණි",
    "portal.attendance": "පැමිණීම",
    "portal.messages": "පණිවිඩ",
    "portal.notifications": "නිවේදන",
    "portal.resources": "සම්පත්",
    "portal.students": "සිසුන්",
    "portal.courses": "පාඨමාලා",
    "portal.logout": "ඉවත් වන්න",
    "portal.signedIn": "පිවිසී සිටින්නේ",
    "portal.openNav": "සංචාලනය විවෘත කරන්න",
    "portal.closeNav": "සංචාලනය වසන්න",
    "page.aboutTitle": "යාපනයේ ප්‍රායෝගික උසස් අධ්‍යාපන කැම්පස් එකක්",
    "page.aboutText": "ATI යාපනය තාක්ෂණික අධ්‍යාපනය, වෘත්තීය මාර්ග සහ වර්ධනය කේන්ද්‍ර කරගත් කැම්පස් සංස්කෘතියක් මඟින් සිසුන්ට සහාය වේ.",
    "page.facultiesText": "ATI යාපනයේ අධ්‍යයන ක්ෂේත්‍ර සොයා බලන්න.",
    "page.coursesTitle": "උසස් ජාතික ඩිප්ලෝමා පාඨමාලා",
    "page.coursesText": "පාඨමාලා මාර්ග සොයා බලා වැඩි විස්තර සඳහා ATI යාපනය අමතන්න.",
    "page.contactTitle": "සම්බන්ධ වන්න",
    "page.contactText": "ATI යාපනය වෙත පණිවිඩයක් යවන්න හෝ සහාය සඳහා කැම්පස් කාර්යාලයට පැමිණෙන්න.",
    "page.fullName": "සම්පූර්ණ නම",
    "page.email": "විද්‍යුත් තැපැල් ලිපිනය",
    "page.subject": "විෂය",
    "page.message": "පණිවිඩය",
    "page.sendMessage": "පණිවිඩය යවන්න",
    "auth.loginTitle": "ඔබේ ATI යාපනය වැඩබිමට පිවිසෙන්න",
    "auth.loginText": "ඔබේ උපකරණ පුවරුව, අධ්‍යයන වාර්තා, නිවේදන සහ ඉගෙනුම් මෙවලම් වෙත පිවිසෙන්න.",
    "auth.official": "නිල ඩිජිටල් වැඩබිම",
    "auth.portalAccess": "ද්වාර ප්‍රවේශය",
    "auth.welcome": "නැවත සාදරයෙන් පිළිගනිමු",
    "auth.welcomeText": "වරක් පිවිසෙන්න; අපි ඔබේ ගිණුම සඳහා නිවැරදි උපකරණ පුවරුව විවෘත කරන්නෙමු.",
    "auth.password": "මුරපදය",
    "auth.passwordPlaceholder": "මුරපදය ඇතුළත් කරන්න",
    "auth.signIn": "පිවිසෙන්න",
    "auth.signingIn": "පිවිසෙමින්...",
    "auth.newUser": "ATI යාපනයට අලුත්ද?",
    "auth.createAccount": "ගිණුමක් සාදන්න",
    "auth.registerTitle": "ඔබේ ATI ද්වාර ගිණුම සාදන්න",
    "auth.registerText": "අධ්‍යයන මාර්ගය, දෙපාර්තමේන්තුව, ඇතුළත් වීම සහ හදිසි සම්බන්ධතා විස්තර සහිත සම්පූර්ණ ශිෂ්‍ය පැතිකඩක් සාදන්න.",
    "auth.studentBenefits": "ශිෂ්‍ය ද්වාර ප්‍රතිලාභ",
    "auth.requestAccess": "ප්‍රවේශය ඉල්ලන්න",
    "auth.requestAccessText": "අධ්‍යයන විස්තර සහිත සක්‍රිය ශිෂ්‍ය ගිණුමක් සාදන්න.",
    "auth.submitRegistration": "ලියාපදිංචිය යොමු කරන්න",
    "auth.creatingAccount": "ගිණුම සාදමින්...",
    "auth.hasAccount": "දැනටමත් ගිණුමක් තිබේද?",
    "portal.student": "ශිෂ්‍ය",
    "portal.admin": "පරිපාලක",
    "portal.faculty": "කථිකාචාර්ය",
    "portal.classTimetable": "පන්ති කාලසටහන",
    "portal.departmentMessages": "දෙපාර්තමේන්තු පණිවිඩ",
    "portal.studentSettings": "ශිෂ්‍ය සැකසුම්",
    "portal.fees": "ගාස්තු",
    "portal.studentProgress": "ශිෂ්‍ය ප්‍රගතිය",
  },
};

const sourceTextKeys = Object.fromEntries(
  Object.entries(translations.en).map(([key, value]) => [value, key]),
);

const LanguageContext = createContext(null);

function readStoredLanguage() {
  const storedLanguage = localStorage.getItem(LANGUAGE_KEY);
  return languageOptions.some(({ code }) => code === storedLanguage) ? storedLanguage : "en";
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(readStoredLanguage);

  useLayoutEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => {
    const t = (key, fallback = key) => translations[language]?.[key] || translations.en[key] || fallback;
    const translate = (text) => {
      if (typeof text !== "string") return text;
      const key = sourceTextKeys[text];
      return key ? t(key, text) : text;
    };

    return { language, setLanguage, t, translate };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider.");
  return context;
}
